/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    news: News;
    offers: Offer;
    gallery: Gallery;
    equipment: Equipment;
    bookings: Booking;
    applications: Application;
    analytics: Analytics;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tu dodajesz terminy widoczne w zakładce Wydarzenia. Wypełnij nazwę, datę, miejsce i krótki opis.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startDate: string;
  /**
   * Zostaw puste przy wydarzeniu jednodniowym.
   */
  endDate?: string | null;
  location: string;
  /**
   * Najważniejsze informacje w 2–4 zdaniach.
   */
  summary: string;
  /**
   * Obowiązkowe. Wybierz zdjęcie pasujące do tego konkretnego wydarzenia.
   */
  image: number | Media;
  category: 'Lato' | 'Zima' | 'Szkolenia' | 'Inne';
  published?: boolean | null;
  /**
   * Opcjonalne. Domyślny tekst jest odpowiedni w większości przypadków.
   */
  ctaLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Biblioteka zdjęć i filmów używanych na stronie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Wiadomości widoczne w zakładce Aktualności. Zdjęcie jest obowiązkowe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  publicationDate: string;
  /**
   * Jedno–dwa zdania widoczne większym tekstem.
   */
  summary: string;
  content: string;
  image: number | Media;
  category: 'Baza' | 'Wyjazdy' | 'Sport' | 'Inne';
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Treści widoczne na stronie głównej i podstronach ofertowych.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  category: 'Lato' | 'Zima' | 'Szkolenia' | 'Noclegi';
  location: string;
  /**
   * 2–4 zdania zachęcające klienta.
   */
  summary: string;
  /**
   * Np. „Sezon 2026”.
   */
  season: string;
  /**
   * Dodaj każdy turnus lub wyjazd jako osobny termin.
   */
  dates?:
    | {
        label?: string | null;
        date: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcjonalne. Bez nowego zdjęcia zostanie obecna fotografia SHOWteam.
   */
  cover?: (number | null) | Media;
  published?: boolean | null;
  staticImage: 'lake' | 'snow' | 'training' | 'stay';
  slug: string;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dodaj zdjęcie lub film, ustaw układ i opublikuj w galerii. Najprościej zrobisz to przez Szybkie dodawanie na pulpicie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image?: (number | null) | Media;
  responsiveSmall?: (number | null) | Media;
  responsiveMedium?: (number | null) | Media;
  staticImage?:
    | (
        | 'summer-wake-aerial'
        | 'summer-double-wake'
        | 'summer-sailing-drone'
        | 'summer-sunset-wake'
        | 'padel'
        | 'ferrata'
        | 'andorra'
        | 'winter-fire'
        | 'trentino'
        | 'instagram-garda'
        | 'instagram-snow'
        | 'instagram-catamarans'
      )
    | null;
  caption: string;
  season: 'Lato' | 'Zima' | 'Szkolenia';
  published?: boolean | null;
  /**
   * Opcjonalne. Pomaga osobom korzystającym z czytnika ekranu.
   */
  alt?: string | null;
  layout: 'large' | 'wide' | 'tall' | 'square';
  mobileLayout: 'landscape' | 'portrait' | 'square';
  fit: 'cover' | 'contain';
  mobilePosition: 'same' | '50% 20%' | '50% 50%' | '50% 80%' | '20% 50%' | '80% 50%';
  /**
   * Opcjonalny link do Instagrama lub Facebooka.
   */
  sourceUrl?: string | null;
  /**
   * Zwykle nie trzeba zmieniać.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Jedyne miejsce zarządzania wynajmem. To, co ustawisz tutaj, automatycznie pojawi się na stronie Rezerwacje, w dostępności i kalendarzu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  name: string;
  /**
   * Napisz krótko, dla kogo jest sprzęt i co warto wiedzieć.
   */
  description: string;
  image?: (number | null) | Media;
  category: 'Woda' | 'Ląd' | 'Szkolenie' | 'Inne';
  quantity: number;
  /**
   * Opcjonalnie, np. „Wymagane uprawnienia”.
   */
  notice?: string | null;
  /**
   * Np. 60 = jedna godzina.
   */
  durationMinutes: number;
  openTime: string;
  closeTime: string;
  active?: boolean | null;
  weatherProfile: 'any' | 'calm' | 'wind';
  recommendedStart1?: string | null;
  recommendedEnd1?: string | null;
  recommendedStart2?: string | null;
  recommendedEnd2?: string | null;
  windMediumMinKmh: number;
  windMediumMaxKmh: number;
  windBestMinKmh: number;
  windBestMaxKmh: number;
  /**
   * Opcjonalne. Działa tylko dla sprzętu, który wymaga wiatru. Zostaw puste, aby wyłączyć.
   */
  professionalWindMinKmh?: number | null;
  recommendationNote?: string | null;
  slug: string;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rezerwacje internetowe. Terminy zmieniaj przez anulowanie i utworzenie nowej rezerwacji, aby nie ominąć kontroli dostępności.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Uwaga: anulowania nie można cofnąć. W razie pomyłki utwórz nową rezerwację.
   */
  status: 'confirmed' | 'completed' | 'cancelled';
  staffNotes?: string | null;
  reference: string;
  reservationId: string;
  equipment: number | Equipment;
  bookingDate: string;
  startTime: string;
  endTime: string;
  customerName: string;
  phone: string;
  email?: string | null;
  customerNotes?: string | null;
  source: 'website' | 'staff';
  updatedAt: string;
  createdAt: string;
}
/**
 * Zgłoszenia wysłane przez formularz na stronie. E-maile potwierdzające zostaną podłączone później.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  status: 'new' | 'contacted' | 'accepted' | 'completed' | 'no_show' | 'cancelled';
  staffNotes?: string | null;
  reference: string;
  offer: string;
  participantName: string;
  participantKey: string;
  birthDate: string;
  address: string;
  email: string;
  normalizedEmail: string;
  participantEmail?: string | null;
  phone: string;
  discipline?: ('Narty' | 'Snowboard' | 'Sporty wodne' | 'Inne') | null;
  level?: ('Od podstaw' | 'Doskonalenie' | 'Jazda sportowa') | null;
  transport?: ('Tak' | 'Nie' | 'Nie dotyczy') | null;
  notes?: string | null;
  privacyConsent: boolean;
  accuracyConfirmed: boolean;
  newsletterConsent?: boolean | null;
  newsletterConsentedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Liczba wizyt w ostatnich 30 dniach. Bez cookies, adresów IP i danych osobowych. Starsze sumy są automatycznie usuwane.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  day: string;
  path: string;
  views: number;
}
/**
 * Osoby, które mogą logować się do panelu SHOWteam.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'analytics';
        value: number | Analytics;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  summary?: T;
  image?: T;
  category?: T;
  published?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  publicationDate?: T;
  summary?: T;
  content?: T;
  image?: T;
  category?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  location?: T;
  summary?: T;
  season?: T;
  dates?:
    | T
    | {
        label?: T;
        date?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  cover?: T;
  published?: T;
  staticImage?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  responsiveSmall?: T;
  responsiveMedium?: T;
  staticImage?: T;
  caption?: T;
  season?: T;
  published?: T;
  alt?: T;
  layout?: T;
  mobileLayout?: T;
  fit?: T;
  mobilePosition?: T;
  sourceUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  category?: T;
  quantity?: T;
  notice?: T;
  durationMinutes?: T;
  openTime?: T;
  closeTime?: T;
  active?: T;
  weatherProfile?: T;
  recommendedStart1?: T;
  recommendedEnd1?: T;
  recommendedStart2?: T;
  recommendedEnd2?: T;
  windMediumMinKmh?: T;
  windMediumMaxKmh?: T;
  windBestMinKmh?: T;
  windBestMaxKmh?: T;
  professionalWindMinKmh?: T;
  recommendationNote?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  status?: T;
  staffNotes?: T;
  reference?: T;
  reservationId?: T;
  equipment?: T;
  bookingDate?: T;
  startTime?: T;
  endTime?: T;
  customerName?: T;
  phone?: T;
  email?: T;
  customerNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  status?: T;
  staffNotes?: T;
  reference?: T;
  offer?: T;
  participantName?: T;
  participantKey?: T;
  birthDate?: T;
  address?: T;
  email?: T;
  normalizedEmail?: T;
  participantEmail?: T;
  phone?: T;
  discipline?: T;
  level?: T;
  transport?: T;
  notes?: T;
  privacyConsent?: T;
  accuracyConfirmed?: T;
  newsletterConsent?: T;
  newsletterConsentedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  day?: T;
  path?: T;
  views?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}