allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260811.1-alpha
  - wrangler@4.123.0
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
overrides:
  "@esbuild-kit/core-utils>esbuild": 0.25.0
  "vite>esbuild": 0.28.2
  dompurify: 3.4.13
