import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footprints, MountainSnow, PartyPopper, Snowflake, UtensilsCrossed } from "lucide-react";
import { ContactCta } from "@/components/contact-cta";
import { CmsDetails } from "@/components/cms-details";
import { OfferAdditionalLocation, OfferCtaTitle, OfferDateList, OfferInlineEditor, OfferLocationLink, OfferText } from "@/components/editor/offer-inline-editor";
import { PageHero } from "@/components/page-hero";
import { PhotoMosaic } from "@/components/photo-mosaic";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { getOfferByCategory } from "@/lib/cms";

export const metadata: Metadata = { title: "Zima 2026/2027", description: "Trentino, Andorra, Pireneje, lodowiec i szkolenie narciarskie.", alternates: { canonical: "/oferta/zima" } };
export const revalidate = false;

export default async function WinterPage() {
  const offer = await getOfferByCategory("Zima");
  if (!offer) notFound();
  return (
    <OfferInlineEditor key={offer.cmsId ?? offer.href} offer={offer}>
      <PageHero eyebrow={`${offer.category} · ${offer.season}`} title={offer.title} description={offer.summary} location={offer.location} image={offer.image} imageAlt={offer.imageAlt} offer={offer} />
      <OfferLocationLink label="Trentino · Dolomity" />
      <OfferAdditionalLocation label="Grandvalira · Andorra" field="winterAndorraMapUrl" fallback="https://www.google.com/maps/search/?api=1&query=Grandvalira+Andorra" />
      <section className="py-20 md:py-28"><div className="site-container grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><Badge><OfferText field="winterDatesBadge" fallback="Zima 2026/2027" /></Badge><h2 className="font-display mt-5 text-6xl font-black uppercase leading-[0.86] tracking-tight sm:text-8xl"><OfferText field="winterDatesTitle" fallback="Śnieg" /><br /><span className="text-sky-300"><OfferText field="winterDatesAccent" fallback="bez granic." /></span></h2><p className="mt-6 max-w-lg leading-7 text-white/55"><OfferText field="winterDatesBody" fallback="Trentino, Andorra i lodowiec w listopadzie. Kolejne terminy pojawią się wkrótce." multiline /></p></div><OfferDateList offer={offer} variant="winter" /></div></section>
      <section className="border-y border-white/10 bg-sky-300 py-20 text-neutral-950 md:py-28"><div className="site-container"><span className="text-xs font-bold uppercase tracking-[0.2em]"><OfferText field="winterPackageEyebrow" fallback="W pakiecie jest więcej niż stok" /></span><h2 className="font-display mt-4 max-w-5xl text-6xl font-black uppercase leading-[0.86] tracking-tight sm:text-8xl"><OfferText field="winterPackageTitle" fallback="Jazda. Przysmaki." /><br /><OfferText field="winterPackageAccent" fallback="Ludzie. Widoki." /></h2><div className="mt-12 grid gap-px overflow-hidden bg-neutral-950/15 sm:grid-cols-2 lg:grid-cols-4">{[[Snowflake,"winterTrainingTitle","Szkolenie","winterTrainingBody","Dzieci, młodzież i dorośli — od podstaw po technikę sportową."],[MountainSnow,"winterRoutesTitle","Trasy","winterRoutesBody","Hotel na stoku, przygotowane trasy i freeride dla chętnych."],[UtensilsCrossed,"winterItalyTitle","Italia","winterItalyBody","Regionalna kuchnia, lokalne smaki i prawdziwa włoska atmosfera."],[PartyPopper,"winterApresTitle","Après-ski","winterApresBody","Garda, trekking, pochodnie, integracja i SHOWniespodzianki."]].map(([Icon,titleField,title,bodyField,text]) => { const I = Icon as typeof Snowflake; return <div key={title as string} className="bg-sky-300 p-7"><I className="size-8" /><h3 className="font-display mt-12 text-3xl font-black uppercase"><OfferText field={titleField as string} fallback={title as string} /></h3><p className="mt-3 text-sm leading-6 text-neutral-800"><OfferText field={bodyField as string} fallback={text as string} multiline /></p></div>; })}</div></div></section>
      <section className="py-20 md:py-28"><div className="site-container grid gap-10 lg:grid-cols-2"><div><Badge><OfferText field="winterAndorraBadge" fallback="Pireneje 2027" /></Badge><h2 className="font-display mt-5 text-6xl font-black uppercase leading-[0.86] tracking-tight sm:text-8xl"><OfferText field="winterAndorraTitle" fallback="Pireneje" /><br /><span className="text-orange-500"><OfferText field="winterAndorraAccent" fallback="+ Barcelona." /></span></h2><div className="mt-8 flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-white/10"><Footprints className="size-6 text-orange-400" /></div><div><p className="font-semibold"><OfferText field="winterAndorraDate" fallback="14–25 marca 2027" /></p><p className="text-sm text-white/45"><OfferText field="winterAndorraLocation" fallback="Andorra i Barcelona" /></p></div></div></div><Accordion type="single" collapsible><AccordionItem value="ski"><AccordionTrigger><OfferText field="winterAndorraSkiTitle" fallback="5 dni na nartach" /></AccordionTrigger><AccordionContent><OfferText field="winterAndorraSkiBody" fallback="Grandvalira oferuje rozległe trasy, freeride i jazdę terenową na wysokości 1710–2640 m n.p.m." multiline /></AccordionContent></AccordionItem><AccordionItem value="after"><AccordionTrigger><OfferText field="winterAndorraAfterTitle" fallback="Po nartach" /></AccordionTrigger><AccordionContent><OfferText field="winterAndorraAfterBody" fallback="Ferraty, psie zaprzęgi, Caldea SPA, Andorra la Vella i wieczorne spotkania z grupą." multiline /></AccordionContent></AccordionItem><AccordionItem value="barcelona"><AccordionTrigger><OfferText field="winterAndorraBarcelonaTitle" fallback="2 dni w Barcelonie" /></AccordionTrigger><AccordionContent><OfferText field="winterAndorraBarcelonaBody" fallback="Bike tour, La Rambla, Sagrada Família, Park Güell oraz lokalne atrakcje wybierane z uczestnikami." multiline /></AccordionContent></AccordionItem></Accordion></div></section>
      <PhotoMosaic offer={offer} label="SHOWzima bez filtra" labelField="winterMosaicLabel" imageFields={["winterMosaicOneImageUrl", "winterMosaicTwoImageUrl", "winterMosaicThreeImageUrl"]} photos={[{ src: "/media/showteam-trentino-collage.jpg", alt: "SHOWteam na zimowym wyjeździe w Trentino", fit: "contain" }, { src: "/media/showteam-andorra-collage.jpg", alt: "Rodzinna SHOWzima w Andorze", fit: "contain" }, { src: "/media/showteam-winter-fire.jpg", alt: "Wieczór z pochodniami na śniegu", fit: "contain" }]} />
      <CmsDetails offer={offer} />
      <ContactCta title={<OfferCtaTitle />} applicationOffer={offer.title} />
    </OfferInlineEditor>
  );
}
