name: Check code style

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false

      - name: Setup pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: template.cfworkers

      - name: Verify code and build
        run: pnpm check && pnpm build
        working-directory: template.cfworkers
