# Common implementation: corioders/cstd-next/.github/workflows/{schedule-runner,deploy}.yml
name: Deploy

on:
  push:
    branches:
      - main
      - payload
      - deploy
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  schedule:
    uses: corioders/cstd-next/.github/workflows/schedule-runner.yml@6cfc58f4dd667e7b280f5622e0636845d339b04e

  application:
    needs: schedule
    uses: corioders/cstd-next/.github/workflows/deploy.yml@6cfc58f4dd667e7b280f5622e0636845d339b04e
    with:
      runner-label: ${{ needs.schedule.outputs.runner-label }}
      app-directory: template.cfworkers
      worker-name: template-cfworkers-web
      preview-worker-name: template-cfworkers-web-preview
      production-cache-bucket: template-cfworkers-next-inc-cache-r2-bucket
      preview-cache-bucket: template-cfworkers-preview-next-inc-cache-r2-bucket
      deploy-enabled: ${{ github.repository != 'corioders/cstd-nextjs-template' }}
      payload: false
    secrets: inherit
